name: build-and-deploy-static-web-page
on: [push]
jobs:
  build-and-package-static:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
  deploy-static:
    runs-on: ubuntu-slim
    needs: build-and-package-static
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}